# Generated by Django 5.2.4 on 2025-10-17 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Systemadmin', '0004_alter_systemadmin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('complaint_text', models.TextField(blank=True, null=True)),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_complaint',
            },
        ),
        migrations.CreateModel(
            name='MilkRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_type', models.CharField(blank=True, choices=[('gir', 'Gir'), ('jershi', 'Jershi'), ('deshi', 'Deshi')], max_length=10, null=True)),
                ('quantity_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_milkrequirement',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('flat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('society_name', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('tal', models.CharField(blank=True, max_length=100, null=True)),
                ('dist', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.CharField(blank=True, max_length=300, null=True)),
                ('cow_milk_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('buffalo_milk_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=100, null=True)),
                ('service_start_date', models.DateField(blank=True, null=True)),
                ('service_end_date', models.DateField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, help_text="Postal code of the customer's address", null=True)),
                ('contact', models.OneToOneField(blank=True, help_text='Reference to the unique phone number.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Systemadmin.uniquephonenumber')),
            ],
            options={
                'db_table': 'customer_customer',
            },
        ),
    ]
