# Generated by Django 5.1.5 on 2025-04-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('society_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wing', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.CharField(blank=True, max_length=10, null=True)),
                ('flat_no', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('create_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_password', models.CharField(blank=True, max_length=100, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=100, null=True)),
                ('milk_quantity', models.CharField(choices=[('half_litre', 'Half Litre'), ('one_litre', 'One Litre'), ('two_litre', 'Two Litre')], default='one_litre', max_length=20)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], default='cow', max_length=10)),
            ],
        ),
    ]
