# Generated by Django 5.1.5 on 2025-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='raise_complaint',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
