# Generated by Django 5.1.5 on 2025-04-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_raise_complaint_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='delivery_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=100),
        ),
    ]
