# Generated by Django 5.1.5 on 2025-04-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
