# Generated by Django 5.2.6 on 2025-10-17 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BusinessRegistration', '0001_initial'),
        ('Customer', '0001_initial'),
        ('Systemadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milkman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('society_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('flat_house', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('tal', models.CharField(blank=True, max_length=100, null=True)),
                ('dist', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, help_text="Postal code of the milkman's address", null=True)),
                ('phone_number', models.OneToOneField(blank=True, help_text='Reference to the unique phone number.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milkman', to='Systemadmin.uniquephonenumber')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milkmen', to='BusinessRegistration.vendorbusinessregistration')),
            ],
            options={
                'db_table': 'milkman_milkman',
            },
        ),
        migrations.CreateModel(
            name='MilkDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], max_length=10)),
                ('quantity_litre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scheduled_time', models.TimeField()),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='Customer.customer')),
                ('milkman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='Milkman.milkman')),
            ],
        ),
    ]
