# Generated by Django 5.1.5 on 2025-04-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0004_flatdetail_owner_contact_flatdetail_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milkman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('assigned_society', models.TextField(blank=True, null=True)),
                ('assigned_flats', models.TextField(blank=True, null=True)),
                ('documents', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milkmen', to='vendor.vendor')),
            ],
        ),
    ]
