# Generated by Django 5.1.5 on 2025-04-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milkman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkman',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='milkman',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
