# Generated by Django 5.1.5 on 2025-04-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milkman', '0002_alter_milkman_contact_number_alter_milkman_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkman',
            name='daily_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='milkman',
            name='owner_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='milkman',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
