# Generated by Django 5.2.4 on 2025-10-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Systemadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBusinessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flat_house', models.CharField(blank=True, max_length=100, null=True)),
                ('society_area', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('tal', models.CharField(blank=True, max_length=100, null=True)),
                ('dist', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, help_text="Postal code of the vendor's address", null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('gir_cow_milk_litre', models.IntegerField(blank=True, null=True)),
                ('jarshi_cow_milk_litre', models.IntegerField(blank=True, null=True)),
                ('deshi_milk_litre', models.IntegerField(blank=True, null=True)),
                ('gir_cow_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gir Cow Rate')),
                ('jarshi_cow_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jarshi Cow Rate')),
                ('deshi_cow_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deshi Cow Rate')),
                ('cr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cow Milk Rate')),
                ('buffalo_milk_litre', models.IntegerField(blank=True, null=True)),
                ('br', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Buffalo Milk rate')),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact', models.OneToOneField(blank=True, help_text='Reference to the unique phone number.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='Systemadmin.uniquephonenumber')),
            ],
            options={
                'db_table': 'businessregistration_vendorbusinessregistration',
            },
        ),
    ]
